//! MQL5 Export — Generate MQL5 EA/Indicator source code from optimizer results.
//!
//! Takes optimized strategy parameters and generates:
//! - .mq5 EA with optimal parameters as input defaults
//! - .set file with parameter values for MT5 Strategy Tester
//! - .mqh indicator if custom indicator needed

/// Strategy parameters optimized by the GPU backtester.
#[derive(Debug, Clone)]
pub struct OptimizedStrategy {
    pub symbol: String,
    pub timeframe: String,
    pub sma_fast: u32,
    pub sma_slow: u32,
    pub rsi_period: u32,
    pub rsi_overbought: f64,
    pub rsi_oversold: f64,
    pub atr_period: u32,
    pub atr_sl_mult: f64,
    pub atr_tp_mult: f64,
    pub sharpe: f64,
    pub profit_factor: f64,
    pub max_drawdown: f64,
    pub win_rate: f64,
    pub trade_count: u32,
    pub robustness_score: f64,
}

/// Generate MQL5 EA source code from optimized parameters.
pub fn generate_ea_source(strategy: &OptimizedStrategy) -> String {
    format!(r#"//+------------------------------------------------------------------+
//| TyphooN SMA Cross EA — GPU-Optimized Parameters                   |
//| Generated by TyphooN Terminal Strategy Optimizer                   |
//| Symbol: {symbol}  Timeframe: {tf}                                  |
//| Sharpe: {sharpe:.2}  PF: {pf:.2}  Win: {win:.1}%  DD: {dd:.1}%  |
//| Robustness: {robust:.2}  Trades: {trades}                         |
//+------------------------------------------------------------------+
#property copyright "TyphooN Risk Management System"
#property link      "https://github.com/TyphooN-"
#property version   "1.00"
#property strict

#include <Orchard\RiskCalc.mqh>

//--- Input parameters (GPU-optimized defaults)
input int    InpFastPeriod     = {fast};       // Fast SMA Period
input int    InpSlowPeriod     = {slow};       // Slow SMA Period
input int    InpRSIPeriod      = {rsi_period};       // RSI Period
input double InpRSIOverbought  = {rsi_ob:.1};    // RSI Overbought Level
input double InpRSIOversold    = {rsi_os:.1};    // RSI Oversold Level
input int    InpATRPeriod      = {atr_period};       // ATR Period
input double InpATRSLMult      = {atr_sl:.2};    // ATR Stop Loss Multiplier
input double InpATRTPMult      = {atr_tp:.2};    // ATR Take Profit Multiplier
input double InpRiskPercent    = 2.0;      // Risk % per trade

//--- Indicator handles
int handleFastSMA, handleSlowSMA, handleRSI, handleATR;

//+------------------------------------------------------------------+
int OnInit()
{{
    handleFastSMA = iMA(_Symbol, PERIOD_CURRENT, InpFastPeriod, 0, MODE_SMA, PRICE_CLOSE);
    handleSlowSMA = iMA(_Symbol, PERIOD_CURRENT, InpSlowPeriod, 0, MODE_SMA, PRICE_CLOSE);
    handleRSI     = iRSI(_Symbol, PERIOD_CURRENT, InpRSIPeriod, PRICE_CLOSE);
    handleATR     = iATR(_Symbol, PERIOD_CURRENT, InpATRPeriod);

    if (handleFastSMA == INVALID_HANDLE || handleSlowSMA == INVALID_HANDLE ||
        handleRSI == INVALID_HANDLE || handleATR == INVALID_HANDLE)
    {{
        Print("Failed to create indicator handles");
        return INIT_FAILED;
    }}
    return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
void OnTick()
{{
    // Only trade on new bar
    static datetime lastBar = 0;
    if (iTime(_Symbol, PERIOD_CURRENT, 0) == lastBar) return;
    lastBar = iTime(_Symbol, PERIOD_CURRENT, 0);

    double fastSMA[2], slowSMA[2], rsi[1], atr[1];
    if (CopyBuffer(handleFastSMA, 0, 1, 2, fastSMA) < 2) return;
    if (CopyBuffer(handleSlowSMA, 0, 1, 2, slowSMA) < 2) return;
    if (CopyBuffer(handleRSI, 0, 1, 1, rsi) < 1) return;
    if (CopyBuffer(handleATR, 0, 1, 1, atr) < 1) return;

    bool hasPosition = PositionSelect(_Symbol);
    double lotSize = RiskCalcLots(_Symbol, InpRiskPercent, atr[0] * InpATRSLMult);

    // Entry: SMA crossover + RSI filter
    if (!hasPosition)
    {{
        // Long: fast crosses above slow, RSI not overbought
        if (fastSMA[0] > slowSMA[0] && fastSMA[1] <= slowSMA[1] && rsi[0] < InpRSIOverbought)
        {{
            double sl = SymbolInfoDouble(_Symbol, SYMBOL_BID) - atr[0] * InpATRSLMult;
            double tp = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + atr[0] * InpATRTPMult;
            MqlTradeRequest req = {{}};
            MqlTradeResult  res = {{}};
            req.action    = TRADE_ACTION_DEAL;
            req.symbol    = _Symbol;
            req.volume    = lotSize;
            req.type      = ORDER_TYPE_BUY;
            req.price     = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            req.sl        = sl;
            req.tp        = tp;
            req.deviation = 20;
            req.magic     = 20260326;
            req.comment   = "TyphooN SMA Cross Long";
            OrderSend(req, res);
        }}
        // Short: fast crosses below slow, RSI not oversold
        else if (fastSMA[0] < slowSMA[0] && fastSMA[1] >= slowSMA[1] && rsi[0] > InpRSIOversold)
        {{
            double sl = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + atr[0] * InpATRSLMult;
            double tp = SymbolInfoDouble(_Symbol, SYMBOL_BID) - atr[0] * InpATRTPMult;
            MqlTradeRequest req = {{}};
            MqlTradeResult  res = {{}};
            req.action    = TRADE_ACTION_DEAL;
            req.symbol    = _Symbol;
            req.volume    = lotSize;
            req.type      = ORDER_TYPE_SELL;
            req.price     = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            req.sl        = sl;
            req.tp        = tp;
            req.deviation = 20;
            req.magic     = 20260326;
            req.comment   = "TyphooN SMA Cross Short";
            OrderSend(req, res);
        }}
    }}
}}

//+------------------------------------------------------------------+
double RiskCalcLots(string symbol, double riskPct, double slDistance)
{{
    double equity = AccountInfoDouble(ACCOUNT_EQUITY);
    double riskAmount = equity * riskPct / 100.0;
    double tickValue = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize  = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
    if (tickValue <= 0 || tickSize <= 0 || slDistance <= 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    double minLot  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
    double maxLot  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
    double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
    lots = MathFloor(lots / lotStep) * lotStep;
    return MathMax(minLot, MathMin(maxLot, lots));
}}
//+------------------------------------------------------------------+
"#,
        symbol = strategy.symbol,
        tf = strategy.timeframe,
        sharpe = strategy.sharpe,
        pf = strategy.profit_factor,
        win = strategy.win_rate * 100.0,
        dd = strategy.max_drawdown * 100.0,
        robust = strategy.robustness_score,
        trades = strategy.trade_count,
        fast = strategy.sma_fast,
        slow = strategy.sma_slow,
        rsi_period = strategy.rsi_period,
        rsi_ob = strategy.rsi_overbought,
        rsi_os = strategy.rsi_oversold,
        atr_period = strategy.atr_period,
        atr_sl = strategy.atr_sl_mult,
        atr_tp = strategy.atr_tp_mult,
    )
}

/// Generate MT5 Strategy Tester .set file with optimized parameters.
pub fn generate_set_file(strategy: &OptimizedStrategy) -> String {
    format!(
        r#"; TyphooN SMA Cross — GPU-Optimized Parameters
; Symbol: {}  Timeframe: {}
; Sharpe: {:.2}  Robustness: {:.2}
InpFastPeriod={}||5||1||50||Y
InpSlowPeriod={}||20||1||200||Y
InpRSIPeriod={}||10||1||30||Y
InpRSIOverbought={:.1}||60||1||90||Y
InpRSIOversold={:.1}||10||1||40||Y
InpATRPeriod={}||7||1||21||Y
InpATRSLMult={:.2}||0.5||0.1||5.0||Y
InpATRTPMult={:.2}||1.0||0.1||8.0||Y
InpRiskPercent=2.0||0.5||0.5||5.0||N
"#,
        strategy.symbol, strategy.timeframe,
        strategy.sharpe, strategy.robustness_score,
        strategy.sma_fast, strategy.sma_slow,
        strategy.rsi_period, strategy.rsi_overbought, strategy.rsi_oversold,
        strategy.atr_period, strategy.atr_sl_mult, strategy.atr_tp_mult,
    )
}

/// Export optimized strategy to files (EA + .set).
pub fn export_strategy(strategy: &OptimizedStrategy, output_dir: &str) -> Result<Vec<String>, String> {
    let dir = std::path::Path::new(output_dir);
    std::fs::create_dir_all(dir).map_err(|e| format!("Create dir failed: {e}"))?;

    let mut exported = Vec::new();

    // Generate EA source
    let ea_source = generate_ea_source(strategy);
    let ea_name = format!("TyphooN_SMA_Cross_{}_{}.mq5", strategy.symbol, strategy.timeframe);
    let ea_path = dir.join(&ea_name);
    std::fs::write(&ea_path, &ea_source).map_err(|e| format!("Write EA failed: {e}"))?;
    exported.push(ea_path.display().to_string());

    // Generate .set file
    let set_content = generate_set_file(strategy);
    let set_name = format!("TyphooN_SMA_Cross_{}_{}.set", strategy.symbol, strategy.timeframe);
    let set_path = dir.join(&set_name);
    std::fs::write(&set_path, &set_content).map_err(|e| format!("Write .set failed: {e}"))?;
    exported.push(set_path.display().to_string());

    Ok(exported)
}
