TyphooN-Terminal Commercial License

Copyright (C) 2023-2026 TyphooN

This document describes the terms under which a commercial license for
TyphooN-Terminal may be obtained. If your use of TyphooN-Terminal exceeds
the Additional Use Grant in the Business Source License 1.1 (see LICENSE),
you must obtain a commercial license under these terms.


1. DEFINITIONS

"Commercial Use" means any use of TyphooN-Terminal (or substantial portions
thereof, including the engine, CLI, compiler, or native GUI) that directly
or indirectly generates revenue, including but not limited to:

  (a) Incorporating into a product or service sold or offered for a fee;
  (b) Using as a component of a trading platform operated for profit
      (proprietary trading for clients, fund management, SaaS);
  (c) Using to execute trades for clients or on behalf of a fund/entity;
  (d) Offering managed accounts, signal services, or copy-trading that
      relies on TyphooN-Terminal;
  (e) Bundling with hardware or other software sold commercially;
  (f) Repackaging, rebranding, or distributing as part of a broker platform
      or trading product offered to third parties.

"Attributable Revenue" means gross revenue directly generated by or through
the product or service that incorporates TyphooN-Terminal, minus payment
processing fees, refunds, and sales tax.

  - For trading firms offering services to clients: management fees and
    performance fees collected from clients.
  - For SaaS platforms: subscription revenue from the product that
    incorporates TyphooN-Terminal.
  - For brokers: revenue from the product or service tier that incorporates
    TyphooN-Terminal (e.g., a premium trading platform tier).
  - If TyphooN-Terminal is one component of a larger product, Attributable
    Revenue equals the product's total revenue multiplied by a reasonable
    allocation percentage, negotiated in good faith. If TyphooN-Terminal is
    the primary component, attribution is 100%.

"Small Use Exemption" means annual Attributable Revenue of $100,000 USD or
less. No commercial license is required for Small Use.


2. ROYALTY STRUCTURE

Commercial licensees shall pay royalties on the following graduated schedule:

  Annual Attributable Revenue        Royalty Rate
  --------------------------------   ----------------------------------------
  $0 - $100,000                      0% (Free - covered by BSL Additional
                                     Use Grant; no commercial license needed)
  $100,001 - $500,000                3% of Attributable Revenue above $100,000
  $500,001 - $2,000,000              3% on $100K-$500K tier, plus
                                     5% of Attributable Revenue above $500,000
  $2,000,001 - $10,000,000           Above tiers, plus
                                     7% of Attributable Revenue above $2,000,000
  Above $10,000,000                  Negotiated flat fee or custom terms -
                                     contact Licensor

Example: A platform generating $1,200,000/year in Attributable Revenue pays:
  First $100,000:                    $0
  $100,001 - $500,000 ($400,000):    $400,000 x 3% = $12,000
  $500,001 - $1,200,000 ($700,000):  $700,000 x 5% = $35,000
  Total annual royalty:              $47,000 (effective rate: ~3.9%)


3. WHAT DOES NOT REQUIRE A COMMERCIAL LICENSE

The following uses are always free and do not require a commercial license:

  (a) Personal trading on your own accounts, regardless of profit or
      account size;
  (b) Internal use at a company where TyphooN-Terminal is used as a tool
      (like using a text editor) and is NOT part of a product or service
      offered to third parties;
  (c) Academic, research, and educational use;
  (d) Use in development, testing, and staging environments;
  (e) Use in other open-source projects licensed under the Change License
      (Apache 2.0) or compatible open-source licenses;
  (f) Any use where annual Attributable Revenue does not exceed $100,000.


4. PAYMENT AND REPORTING

  (a) Reporting Period: Calendar quarters (Q1: Jan-Mar, Q2: Apr-Jun,
      Q3: Jul-Sep, Q4: Oct-Dec).
  (b) Payment Due: Within 45 days after the end of each calendar quarter.
  (c) Revenue Report: Licensee shall provide a written report showing
      Attributable Revenue for the quarter, in reasonable detail.
  (d) Currency: All amounts in USD.
  (e) Late Payment: Interest of 1.5% per month on overdue amounts.
  (f) Minimum Term: 1 year from execution, auto-renewing annually unless
      terminated with 90 days written notice.


5. AUDIT RIGHTS

Licensor may request an independent audit of Licensee's Attributable Revenue
records once per calendar year. The audit shall be conducted by a mutually
agreed-upon independent auditor. Licensor bears the cost of the audit unless
the audit reveals an underpayment exceeding 10% of the amount actually owed,
in which case Licensee bears the audit cost and shall promptly pay the
shortfall plus interest.


6. GRACE PERIODS AND COMPLIANCE

  (a) Evaluation Period: New commercial users have 90 days from first
      production deployment to execute a commercial license.
  (b) Cure Period: If a party discovers non-compliance, the non-compliant
      party has 60 days from written notice to execute a commercial license
      and pay any back-royalties from the date commercial use began. No
      penalties apply during this cure period.
  (c) Willful Infringement: If a party knowingly uses TyphooN-Terminal in
      violation of the BSL and this Commercial License and fails to cure
      within the 60-day period, Licensor reserves all rights and remedies
      available under applicable law, including injunctive relief and
      damages.


7. GRANT OF RIGHTS

Upon execution of a commercial license and payment of applicable royalties,
Licensor grants Licensee:

  (a) A non-exclusive, worldwide license to use, modify, and distribute
      TyphooN-Terminal in proprietary products without source disclosure;
  (b) The right to create derivative works without open-sourcing them;
  (c) No requirement to display BSL notices in the Licensee's product
      (though attribution is appreciated);
  (d) Priority consideration for bug fixes and feature requests.


8. TERMINATION

  (a) Either party may terminate with 90 days written notice at the end of
      any annual term.
  (b) Licensor may terminate immediately upon material breach that is not
      cured within the 60-day cure period.
  (c) Upon termination, Licensee must cease commercial use of versions
      still under BSL (versions past their Change Date are Apache 2.0 and
      unaffected).
  (d) Sections 1, 5, and 9 survive termination.


9. LIMITATION OF LIABILITY

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
LICENSOR BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED
DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER
INTANGIBLE LOSSES, RESULTING FROM (A) YOUR USE OR INABILITY TO USE THE
LICENSED WORK; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY; OR
(C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF THE LICENSED WORK.


10. CONTACT

For commercial licensing inquiries, contact the Licensor through the project
repository or release channel.
