use super::*;

impl TyphooNApp {
    /// Build session JSON string (pure data, no I/O — safe to call from UI thread).
    pub(in crate::app) fn build_session_json(&self) -> String {
        let session = self.build_session_value();
        serde_json::to_string_pretty(&session).unwrap_or_default()
    }

    pub(super) fn build_session_value(&self) -> serde_json::Value {
        let persisted_tabs: Vec<_> = self
            .charts
            .iter()
            .filter(|chart| chart.show_in_tab_bar)
            .collect();
        let persisted_active_tab = self
            .charts
            .iter()
            .enumerate()
            .filter(|(_, chart)| chart.show_in_tab_bar)
            .position(|(idx, _)| idx == self.active_tab)
            .unwrap_or(0);
        serde_json::json!({
            "symbol": self.symbol_input,
            "active_tab": persisted_active_tab,
            "tabs": persisted_tabs.iter().map(|c| serde_json::json!({
                "symbol": c.symbol,
                "timeframe": c.timeframe.label(),
                "chart_type": c.chart_type.label(),
                "log_scale": c.log_scale,
                "visible_bars": c.visible_bars,
                "view_offset": c.view_offset,
            })).collect::<Vec<_>>(),
            "indicators": {
                "sma200": self.show_sma200, "sma100": self.show_sma100,
                "kama": self.show_kama, "ema21": self.show_ema21,
                "bollinger": self.show_bollinger, "ichimoku": self.show_ichimoku,
                "wma": self.show_wma, "hma": self.show_hma,
                "psar": self.show_psar, "atr_proj": self.show_atr_proj,
                "prev_levels": self.show_prev_levels, "pivots": self.show_pivots,
                "fractals": self.show_fractals, "harmonics": self.show_harmonics, "supply_demand": self.show_supply_demand,
                "ehlers_ss": self.show_ehlers_ss, "ehlers_decycler": self.show_ehlers_decycler,
                "ehlers_itl": self.show_ehlers_itl, "ehlers_mama": self.show_ehlers_mama,
                "ehlers_ebsw": self.show_ehlers_ebsw, "ehlers_cyber": self.show_ehlers_cyber,
                "ehlers_cg": self.show_ehlers_cg, "ehlers_roof": self.show_ehlers_roof,
                "rsi": self.show_rsi, "fisher": self.show_fisher,
                "macd": self.show_macd, "stochastic": self.show_stochastic,
                "adx": self.show_adx, "cci": self.show_cci,
                "williams_r": self.show_williams_r, "obv": self.show_obv,
                "momentum": self.show_momentum, "cmo": self.show_cmo,
                "qstick": self.show_qstick, "disparity": self.show_disparity,
                "bop": self.show_bop, "stddev": self.show_stddev,
                "mfi": self.show_mfi, "trix": self.show_trix,
                "ppo": self.show_ppo, "ultosc": self.show_ultosc,
                "stochrsi": self.show_stochrsi,
                "var_oscillator": self.show_var_oscillator,
                "better_volume": self.show_better_volume,
                "volume_pane": self.show_volume_pane, "sessions": self.show_sessions,
                "vol_heatmap": self.show_vol_heatmap, "vwap": self.show_vwap,
                "price_histogram": self.show_price_histogram,
                "supertrend": self.show_supertrend, "donchian": self.show_donchian, "keltner": self.show_keltner,
                "regression": self.show_regression, "squeeze": self.show_squeeze,
                "fvg": self.show_fvg, "order_blocks": self.show_order_blocks,
            },
            "mtf_enabled": self.mtf_enabled,
            "mtf_cols": self.mtf_cols,
            "mtf_visible": self.mtf_visible,
            "kraken_scrape_schema": 3,
            "kraken_scrape_xstocks": self.kraken_scrape_xstocks,
            "kraken_scrape_usd_crypto": self.kraken_scrape_usd_crypto,
            "kraken_scrape_fiat_crypto": self.kraken_scrape_fiat_crypto,
            "kraken_scrape_crypto_crosses": self.kraken_scrape_crypto_crosses,
            "kraken_scrape_futures": self.kraken_scrape_futures,
            "alpaca_full_bar_sync_enabled": self.alpaca_full_bar_sync_enabled,
            "kraken_full_bar_sync_enabled": self.kraken_full_bar_sync_enabled,
            "backfill_alpaca_kraken_equities_enabled": self.backfill_alpaca_kraken_equities_enabled,
            "backfill_yahoo_chart_enabled": self.backfill_yahoo_chart_enabled,
            "kraken_ws_ohlc_enabled": self.kraken_ws_ohlc_enabled,
            "crypto_fiat_quote_usd": self.crypto_fiat_quote_usd,
            "crypto_fiat_quote_usdt": self.crypto_fiat_quote_usdt,
            "crypto_fiat_quote_usdc": self.crypto_fiat_quote_usdc,
            "crypto_fiat_quote_usdg": self.crypto_fiat_quote_usdg,
            "crypto_fiat_quote_eur": self.crypto_fiat_quote_eur,
            "crypto_fiat_quote_gbp": self.crypto_fiat_quote_gbp,
            "crypto_fiat_quote_cad": self.crypto_fiat_quote_cad,
            "crypto_fiat_quote_aud": self.crypto_fiat_quote_aud,
            "crypto_fiat_quote_jpy": self.crypto_fiat_quote_jpy,
            "crypto_fiat_quote_chf": self.crypto_fiat_quote_chf,
            "enabled_sync_timeframes": STANDARD_SYNC_TIMEFRAMES.iter()
                .filter_map(|(_, tf)| self.enabled_sync_timeframes.contains(*tf).then(|| serde_json::json!(tf)))
                .collect::<Vec<_>>(),
            "alpaca_historical_rpm_hint": self.alpaca_historical_rpm_hint,
            "command_open": self.command_open,
            "compact_mode": self.compact_mode,
            "broker_scope": match self.broker_scope {
                EventSource::All => "all",
                EventSource::Alpaca => "alpaca",
                EventSource::Kraken => "kraken",
                EventSource::Positions => "positions",
            },
            "econ_filter_high": self.econ_filter_high,
            "econ_filter_medium": self.econ_filter_medium,
            "econ_filter_low": self.econ_filter_low,
            "econ_filter_holiday": self.econ_filter_holiday,
            "econ_filter_currencies": self.econ_filter_currencies,
            "right_tab": match self.right_tab {
                RightTab::Trading => "trading",
                RightTab::Positions => "positions",
                RightTab::Orders => "orders",
                RightTab::Watchlist => "watchlist",
                RightTab::Risk => "risk",
            },
            "right_trading_open": self.right_trading_open,
            "right_positions_open": self.right_positions_open,
            "right_orders_open": self.right_orders_open,
            "right_watchlist_open": self.right_watchlist_open,
            "right_risk_open": self.right_risk_open,
            "right_recent_fills_open": self.right_recent_fills_open,
            "right_news_open": self.right_news_open,
            "news_search_query": self.news_search_query,
            "news_selected_url_hash": self.news_selected
                .and_then(|idx| self.news_full_articles.get(idx))
                .map(|a| a.url_hash.clone())
                .unwrap_or_else(|| self.news_selected_url_hash.clone()),
            "right_mtf_grid_open": self.right_mtf_grid_open,
            "right_panel_order": self.right_panel_order.iter()
                .map(|section| serde_json::json!(section.as_str()))
                .collect::<Vec<_>>(),
            "user_watchlist": self.user_watchlist,
            "sma_outfits": self.sma_outfits,
            "workspaces": serde_json::Value::Object(
                self.workspaces.iter()
                    .map(|(k, v)| (k.clone(), serde_json::json!(v)))
                    .collect()
            ),
            "show_alpaca_positions": self.show_alpaca_positions,
            "show_kr_positions": self.show_kr_positions,
            "snap_enabled": self.snap_enabled,
            "cross_tf_drawings": self.cross_tf_drawings,
            "follow_latest": self.follow_latest,
            "draw_width": self.draw_width,
            "draw_color": [self.draw_color.r(), self.draw_color.g(), self.draw_color.b()],
            "draw_line_style": match self.draw_line_style { LineStyle::Solid => "solid", LineStyle::Dashed => "dashed", LineStyle::Dotted => "dotted" },
            "codex_model": self.codex_model,
            "codex_reasoning_effort": self.codex_reasoning_effort,
            "hermes_model": self.hermes_model,
            "hermes_provider": self.hermes_provider,
            "grok_model": self.grok_model,
            "grok_effort": self.grok_effort,
            // Credentials: keyring-only (secure OS storage). Session stores non-secret config.
            "alpaca_enabled": self.alpaca_enabled,
            "alpaca_full_bar_sync_enabled": self.alpaca_full_bar_sync_enabled,
            "kraken_enabled": self.kraken_enabled,
            "kraken_full_bar_sync_enabled": self.kraken_full_bar_sync_enabled,
            "broker_paper": self.broker_paper,
            "sl_enabled": self.sl_enabled,
            "tp_enabled": self.tp_enabled,
            "windows": {
                "settings": self.show_settings,
                "risk_calc": self.show_risk_calc,
                "compound_calc": self.show_compound_calc,
                "calendar": self.show_calendar,
                "backtest": self.show_backtest,
                "news": self.show_news,
                "indicators_panel": self.show_indicators_panel,
                "screener": self.show_screener,
                "symbols": self.show_symbols,
                "optimizer": self.show_optimizer,
                "ai_chat": self.show_ai_chat,
                "claude_code": self.show_claude_code,
                "antigravity_cli": self.show_antigravity_cli,
                "codex_cli": self.show_codex_cli,
                "hermes_cli": self.show_hermes_cli,
                "grok_cli": self.show_grok_cli,
                "matrix_chat": self.show_matrix_chat,
                "sec": self.show_sec,
                "insider": self.show_insider,
                "fundamentals": self.show_fundamentals,
                "order_flow": self.show_order_flow,
                "bookmap": self.show_bookmap,
                "journal": self.show_journal,
                "var_mult": self.show_var_mult,
                "montecarlo": self.show_montecarlo,
                "earnings_calendar": self.show_earnings_calendar,
                "dividend_calendar": self.show_dividend_calendar,
                "event_calendar": self.show_event_calendar,
                "ev_scanner": self.show_ev_scanner,
                "stress_test": self.show_stress_test,
                "volume_profile": self.show_volume_profile,
                "depth_profile": self.show_depth_profile,
                "hv_cone": self.show_hv_cone,
                "sector_heatmap": self.show_sector_heatmap,
                "dividends_screen": self.show_dividends,
                "company_info": self.show_company_info_window,
                "alert_builder": self.show_alert_builder,
                "storage": self.show_storage,
                "sync_status": self.show_sync_status,
                "unusual_volume": self.show_unusual_volume,
                "sector_rotation": self.show_sector_rotation,
                "fred": self.show_fred,
                "econ_calendar": self.show_econ_calendar,
                "congress": self.show_congress,
                "world_indices": self.show_world_indices,
                "crypto_top50": self.show_crypto_top50,
                "forex_matrix": self.show_forex_matrix,
                "help": self.show_help,
                "connect": self.show_connect,
                "data_window": self.show_data_window,
                "alerts": self.show_alerts,
                "scope_window": self.show_scope_window,
                "scrape_status": self.show_scrape_status,
                "fear_greed": self.show_fear_greed,
            },
            "journal": self.journal_entries.iter().map(|e| serde_json::json!({
                "timestamp": e.timestamp, "symbol": e.symbol, "side": e.side,
                "qty": e.qty, "entry_price": e.entry_price,
                "exit_price": e.exit_price, "pnl": e.pnl,
                "strategy": e.strategy, "notes": e.notes,
            })).collect::<Vec<_>>(),
            "drawings": self.charts.get(0).map(|c| {
                c.drawings.iter().filter_map(|d| match d {
                    Drawing::HLine { price, color } => Some(serde_json::json!({"type":"hline","price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::VLine { bar_idx, color } => Some(serde_json::json!({"type":"vline","bar_idx":bar_idx,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::TrendLine { p1, p2, color } => Some(serde_json::json!({"type":"trendline","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::FiboRetrace { high, low, bar_start, bar_end } => Some(serde_json::json!({"type":"fibo","high":high,"low":low,"bar_start":bar_start,"bar_end":bar_end})),
                    Drawing::Rectangle { p1, p2, color } => Some(serde_json::json!({"type":"rect","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Ray { origin, slope, color } => Some(serde_json::json!({"type":"ray","origin":[origin.0,origin.1],"slope":slope,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Channel { p1, p2, width, color } => Some(serde_json::json!({"type":"channel","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"width":width,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ExtendedLine { p1, p2, color } => Some(serde_json::json!({"type":"extline","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::HRay { bar_idx, price, color } => Some(serde_json::json!({"type":"hray","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::CrossLine { bar_idx, price, color } => Some(serde_json::json!({"type":"crossline","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ArrowLine { p1, p2, color } => Some(serde_json::json!({"type":"arrowline","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::InfoLine { p1, p2, color } => Some(serde_json::json!({"type":"infoline","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Pitchfork { pivot, p2, p3, color } => Some(serde_json::json!({"type":"pitchfork","pivot":[pivot.0,pivot.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::FiboExtension { p1, p2, p3, color } => Some(serde_json::json!({"type":"fiboext","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::GannFan { origin, scale, color } => Some(serde_json::json!({"type":"gannfan","origin":[origin.0,origin.1],"scale":scale,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::LongPosition { entry, stop, target } => Some(serde_json::json!({"type":"longpos","entry":[entry.0,entry.1],"stop":stop,"target":target})),
                    Drawing::ShortPosition { entry, stop, target } => Some(serde_json::json!({"type":"shortpos","entry":[entry.0,entry.1],"stop":stop,"target":target})),
                    Drawing::PriceRange { p1, p2 } => Some(serde_json::json!({"type":"pricerange","p1":[p1.0,p1.1],"p2":[p2.0,p2.1]})),
                    Drawing::TextLabel { bar_idx, price, text, color } => Some(serde_json::json!({"type":"text","bar_idx":bar_idx,"price":price,"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ArrowMarker { bar_idx, price, is_up, color } => Some(serde_json::json!({"type":"arrowmarker","bar_idx":bar_idx,"price":price,"is_up":is_up,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Ellipse { p1, p2, color } => Some(serde_json::json!({"type":"ellipse","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Triangle { p1, p2, p3, color } => Some(serde_json::json!({"type":"triangle","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::TrendAngle { p1, p2, color } => Some(serde_json::json!({"type":"trendangle","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ParallelChannel { p1, p2, offset, color } => Some(serde_json::json!({"type":"parallelch","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"offset":offset,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::FibChannel { p1, p2, p3, color } => Some(serde_json::json!({"type":"fibchannel","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::FibTimeZones { bar_idx, color } => Some(serde_json::json!({"type":"fibtimezones","bar_idx":bar_idx,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::PriceLabel { bar_idx, price, color } => Some(serde_json::json!({"type":"pricelabel","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Callout { anchor, label_pos, text, color } => Some(serde_json::json!({"type":"callout","anchor":[anchor.0,anchor.1],"label_pos":[label_pos.0,label_pos.1],"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Highlighter { p1, p2, color } => Some(serde_json::json!({"type":"highlighter","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::CrossMarker { bar_idx, price, color } => Some(serde_json::json!({"type":"crossmarker","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Polyline { points, color } => Some(serde_json::json!({"type":"polyline","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::AnchorNote { bar_idx, price, text, color } => Some(serde_json::json!({"type":"anchornote","bar_idx":bar_idx,"price":price,"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::RegressionChannel { p1, p2, color } => Some(serde_json::json!({"type":"regressionch","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::GannBox { p1, p2, color } => Some(serde_json::json!({"type":"gannbox","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ElliottWave { points, color } => Some(serde_json::json!({"type":"elliott","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::AbcCorrection { points, color } => Some(serde_json::json!({"type":"abc","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::DateRange { p1, p2 } => Some(serde_json::json!({"type":"daterange","p1":[p1.0,p1.1],"p2":[p2.0,p2.1]})),
                    Drawing::DatePriceRange { p1, p2 } => Some(serde_json::json!({"type":"datepricerange","p1":[p1.0,p1.1],"p2":[p2.0,p2.1]})),
                    Drawing::HeadShoulders { points, color } => Some(serde_json::json!({"type":"headshoulders","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::XabcdPattern { points, color } => Some(serde_json::json!({"type":"xabcd","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Brush { points, color } => Some(serde_json::json!({"type":"brush","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::SchiffPitchfork { pivot, p2, p3, color } => Some(serde_json::json!({"type":"schiffpitchfork","pivot":[pivot.0,pivot.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ModSchiffPitchfork { pivot, p2, p3, color } => Some(serde_json::json!({"type":"modschiffpitchfork","pivot":[pivot.0,pivot.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::CyclicLines { bar_start, bar_end, color } => Some(serde_json::json!({"type":"cycliclines","bar_start":bar_start,"bar_end":bar_end,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::SineWave { p1, p2, color } => Some(serde_json::json!({"type":"sinewave","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Emoji { bar_idx, price, emoji } => Some(serde_json::json!({"type":"emoji","bar_idx":bar_idx,"price":price,"emoji":emoji})),
                    Drawing::Flag { bar_idx, price, color } => Some(serde_json::json!({"type":"flag","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Balloon { anchor, label_pos, text, color } => Some(serde_json::json!({"type":"balloon","anchor":[anchor.0,anchor.1],"label_pos":[label_pos.0,label_pos.1],"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::SessionBreak { bar_idx, color } => Some(serde_json::json!({"type":"sessionbreak","bar_idx":bar_idx,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::MagnetLevel { price, color } => Some(serde_json::json!({"type":"magnetlevel","price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::RiskRewardBox { entry, stop, target } => Some(serde_json::json!({"type":"riskreward","entry":[entry.0,entry.1],"stop":stop,"target":target})),
                    Drawing::FibCircle { center, radius_pt, color } => Some(serde_json::json!({"type":"fibcircle","center":[center.0,center.1],"radius_pt":[radius_pt.0,radius_pt.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ArcDraw { p1, p2, p3, color } => Some(serde_json::json!({"type":"arcdraw","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::CurveDraw { p1, ctrl1, ctrl2, p2, color } => Some(serde_json::json!({"type":"curvedraw","p1":[p1.0,p1.1],"ctrl1":[ctrl1.0,ctrl1.1],"ctrl2":[ctrl2.0,ctrl2.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::PathDraw { points, color } => Some(serde_json::json!({"type":"pathdraw","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Forecast { p1, p2, color } => Some(serde_json::json!({"type":"forecast","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::GhostFeed { p1, p2, color } => Some(serde_json::json!({"type":"ghostfeed","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Signpost { bar_idx, price, color } => Some(serde_json::json!({"type":"signpost","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Ruler { p1, p2, color } => Some(serde_json::json!({"type":"ruler","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::TimeCycle { bar_start, bar_end, color } => Some(serde_json::json!({"type":"timecycle","bar_start":bar_start,"bar_end":bar_end,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::SpeedResistanceFan { p1, p2, p3, color } => Some(serde_json::json!({"type":"speedfan","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::SpeedResistanceArc { p1, p2, p3, color } => Some(serde_json::json!({"type":"speedarc","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::FibSpiral { center, radius_pt, color } => Some(serde_json::json!({"type":"fibspiral","center":[center.0,center.1],"radius_pt":[radius_pt.0,radius_pt.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::RotatedRectangle { p1, p2, p3, color } => Some(serde_json::json!({"type":"rotatedrect","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::AnchoredVwapLine { bar_idx, color } => Some(serde_json::json!({"type":"anchoredvwap","bar_idx":bar_idx,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::TrendChannel { p1, p2, p3, color } => Some(serde_json::json!({"type":"trendchannel","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::InsidePitchfork { pivot, p2, p3, color } => Some(serde_json::json!({"type":"insidepitchfork","pivot":[pivot.0,pivot.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::FibWedge { p1, p2, p3, color } => Some(serde_json::json!({"type":"fibwedge","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"p3":[p3.0,p3.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::PriceNote { price, text, color } => Some(serde_json::json!({"type":"pricenote","price":price,"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::MeasureTool { p1, p2, color } => Some(serde_json::json!({"type":"measuretool","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::AnchoredText { bar_idx, price, text, color } => Some(serde_json::json!({"type":"anchoredtext","bar_idx":bar_idx,"price":price,"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Comment { bar_idx, price, text, color } => Some(serde_json::json!({"type":"comment","bar_idx":bar_idx,"price":price,"text":text,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ArrowMarkerLeft { bar_idx, price, color } => Some(serde_json::json!({"type":"arrowleft","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ArrowMarkerRight { bar_idx, price, color } => Some(serde_json::json!({"type":"arrowright","bar_idx":bar_idx,"price":price,"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Circle { p1, p2, color } => Some(serde_json::json!({"type":"circle","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::PitchFan { p1, p2, color } => Some(serde_json::json!({"type":"pitchfan","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::TrendFibTime { p1, p2, color } => Some(serde_json::json!({"type":"trendfibtime","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::GannSquare { p1, p2, color } => Some(serde_json::json!({"type":"gannsquare","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::GannSquareFixed { p1, p2, color } => Some(serde_json::json!({"type":"gannsquarefixed","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::BarsPattern { p1, p2, color } => Some(serde_json::json!({"type":"barspattern","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::Projection { p1, p2, color } => Some(serde_json::json!({"type":"projection","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::DoubleCurve { p1, p2, color } => Some(serde_json::json!({"type":"doublecurve","p1":[p1.0,p1.1],"p2":[p2.0,p2.1],"color":[color.r(),color.g(),color.b()]})),
                    Drawing::TrianglePattern { points, color } => Some(serde_json::json!({"type":"trianglepattern","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ThreeDrives { points, color } => Some(serde_json::json!({"type":"threedrives","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ElliottDouble { points, color } => Some(serde_json::json!({"type":"elliottdouble","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::AbcdPattern { points, color } => Some(serde_json::json!({"type":"abcd","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::CypherPattern { points, color } => Some(serde_json::json!({"type":"cypher","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ElliottTriangle { points, color } => Some(serde_json::json!({"type":"elliotttriangle","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                    Drawing::ElliottTripleCombo { points, color } => Some(serde_json::json!({"type":"elliotttriple","points":points.iter().map(|p| serde_json::json!([p.0, p.1])).collect::<Vec<_>>(),"color":[color.r(),color.g(),color.b()]})),
                }).collect::<Vec<_>>()
            }).unwrap_or_default(),
            "alerts": self.alerts.iter().map(|(p, l)| serde_json::json!({"price": p, "label": l})).collect::<Vec<_>>(),
            "chart_templates": self.chart_templates.iter().map(|(k, v)| (k.clone(), v.clone())).collect::<serde_json::Map<String, serde_json::Value>>(),
        })
    }

    /// Returns true for crypto symbols (sourced from Kraken). Used by the
    /// weekend crypto-sync scheduler and symbol-universe classification.
    pub(in crate::app) fn demand_is_crypto(sym: &str) -> bool {
        let crypto_bases = [
            "BTC", "ETH", "SOL", "DOGE", "XRP", "ADA", "LTC", "LINK", "AVAX", "DOT", "XMR", "ZEC",
            "DASH", "UNI", "AAVE", "MATIC", "SHIB", "ATOM", "ALGO", "FTM", "NEAR", "APE", "ARB",
            "OP", "MKR", "COMP", "SNX", "CRV", "SUSHI", "YFI", "BAT", "MANA", "SAND", "AXS", "BCH",
            "ETC", "XLM", "FIL", "HBAR", "ICP", "VET", "THETA",
        ];
        let su = sym.to_uppercase();
        crypto_bases.iter().any(|b| {
            su.starts_with(b)
                && (su.ends_with("USD") || su.ends_with("USDT") || su.ends_with("BTC"))
        })
    }
}
